apiVersion: openshiftcontrolplane.config.openshift.io/v1
build:
  additionalTrustedCA: ""
  buildDefaults: null
  buildOverrides: null
  imageTemplateFormat:
    format: ""
    latest: false
controllers: null
deployer:
  imageTemplateFormat:
    format: ""
    latest: false
dockerPullSecret:
  internalRegistryHostname: ""
  registryURLs: null
imageImport:
  disableScheduledImport: false
  maxScheduledImageImportsPerMinute: 0
  scheduledImageImportMinimumIntervalSeconds: 0
ingress:
  ingressIPNetworkCIDR: ""
kind: OpenShiftControllerManagerConfig
kubeClientConfig:
  connectionOverrides:
    acceptContentTypes: ""
    burst: 0
    contentType: ""
    qps: 0
  kubeConfig: ""
leaderElection:
  leaseDuration: 0s
  renewDeadline: 0s
  retryPeriod: 0s
network:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  networkPluginName: redhat/openshift-ovs-networkpolicy
  serviceNetworkCIDR: 172.30.0.0/16
  vxlanPort: 4789
resourceQuota:
  concurrentSyncs: 0
  minResyncPeriod: 0s
  syncPeriod: 0s
securityAllocator:
  mcsAllocatorRange: ""
  mcsLabelsPerProject: 0
  uidAllocatorRange: ""
serviceAccount:
  managedNames: null
serviceServingCert:
  signer: null
servingInfo: nullsh-4.2$ cat controller-config.yaml 
apiVersion: openshiftcontrolplane.config.openshift.io/v1
build:
  additionalTrustedCA: ""
  buildDefaults: null
  buildOverrides: null
  imageTemplateFormat:
    format: ""
    latest: false
controllers: null
deployer:
  imageTemplateFormat:
    format: ""
    latest: false
dockerPullSecret:
  internalRegistryHostname: ""
  registryURLs: null
imageImport:
  disableScheduledImport: false
  maxScheduledImageImportsPerMinute: 0
  scheduledImageImportMinimumIntervalSeconds: 0
ingress:
  ingressIPNetworkCIDR: ""
kind: OpenShiftControllerManagerConfig
kubeClientConfig:
  connectionOverrides:
    acceptContentTypes: ""
    burst: 0
    contentType: ""
    qps: 0
  kubeConfig: ""
leaderElection:
  leaseDuration: 0s
  renewDeadline: 0s
  retryPeriod: 0s
network:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  networkPluginName: redhat/openshift-ovs-networkpolicy
  serviceNetworkCIDR: 172.30.0.0/16
  vxlanPort: 4789
resourceQuota:
  concurrentSyncs: 0
  minResyncPeriod: 0s
  syncPeriod: 0s
securityAllocator:
  mcsAllocatorRange: ""
  mcsLabelsPerProject: 0
  uidAllocatorRange: ""
serviceAccount:
  managedNames: null
serviceServingCert:
  signer: null


